// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: access.proto

package accesspb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListReposRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgName       string                 `protobuf:"bytes,1,opt,name=org_name,json=orgName,proto3" json:"org_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReposRequest) Reset() {
	*x = ListReposRequest{}
	mi := &file_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReposRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReposRequest) ProtoMessage() {}

func (x *ListReposRequest) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReposRequest.ProtoReflect.Descriptor instead.
func (*ListReposRequest) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{0}
}

func (x *ListReposRequest) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

type RepoAccessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoName      string                 `protobuf:"bytes,1,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	AllowedUsers  []string               `protobuf:"bytes,2,rep,name=allowed_users,json=allowedUsers,proto3" json:"allowed_users,omitempty"`
	BlockedUsers  []string               `protobuf:"bytes,3,rep,name=blocked_users,json=blockedUsers,proto3" json:"blocked_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoAccessInfo) Reset() {
	*x = RepoAccessInfo{}
	mi := &file_access_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoAccessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoAccessInfo) ProtoMessage() {}

func (x *RepoAccessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoAccessInfo.ProtoReflect.Descriptor instead.
func (*RepoAccessInfo) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{1}
}

func (x *RepoAccessInfo) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *RepoAccessInfo) GetAllowedUsers() []string {
	if x != nil {
		return x.AllowedUsers
	}
	return nil
}

func (x *RepoAccessInfo) GetBlockedUsers() []string {
	if x != nil {
		return x.BlockedUsers
	}
	return nil
}

type ListReposResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repos         []*RepoAccessInfo      `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReposResponse) Reset() {
	*x = ListReposResponse{}
	mi := &file_access_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReposResponse) ProtoMessage() {}

func (x *ListReposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReposResponse.ProtoReflect.Descriptor instead.
func (*ListReposResponse) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{2}
}

func (x *ListReposResponse) GetRepos() []*RepoAccessInfo {
	if x != nil {
		return x.Repos
	}
	return nil
}

var File_access_proto protoreflect.FileDescriptor

const file_access_proto_rawDesc = "" +
	"\n" +
	"\faccess.proto\x12\aaccessp\x1a\x1cgoogle/api/annotations.proto\"-\n" +
	"\x10ListReposRequest\x12\x19\n" +
	"\borg_name\x18\x01 \x01(\tR\aorgName\"w\n" +
	"\x0eRepoAccessInfo\x12\x1b\n" +
	"\trepo_name\x18\x01 \x01(\tR\brepoName\x12#\n" +
	"\rallowed_users\x18\x02 \x03(\tR\fallowedUsers\x12#\n" +
	"\rblocked_users\x18\x03 \x03(\tR\fblockedUsers\"B\n" +
	"\x11ListReposResponse\x12-\n" +
	"\x05repos\x18\x01 \x03(\v2\x17.accessp.RepoAccessInfoR\x05repos2m\n" +
	"\rAccessService\x12\\\n" +
	"\tListRepos\x12\x19.accessp.ListReposRequest\x1a\x1a.accessp.ListReposResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/list/{org_name}B,Z*github.com/nikkmidl/rig-api/proto/accesspbb\x06proto3"

var (
	file_access_proto_rawDescOnce sync.Once
	file_access_proto_rawDescData []byte
)

func file_access_proto_rawDescGZIP() []byte {
	file_access_proto_rawDescOnce.Do(func() {
		file_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_access_proto_rawDesc), len(file_access_proto_rawDesc)))
	})
	return file_access_proto_rawDescData
}

var file_access_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_access_proto_goTypes = []any{
	(*ListReposRequest)(nil),  // 0: accessp.ListReposRequest
	(*RepoAccessInfo)(nil),    // 1: accessp.RepoAccessInfo
	(*ListReposResponse)(nil), // 2: accessp.ListReposResponse
}
var file_access_proto_depIdxs = []int32{
	1, // 0: accessp.ListReposResponse.repos:type_name -> accessp.RepoAccessInfo
	0, // 1: accessp.AccessService.ListRepos:input_type -> accessp.ListReposRequest
	2, // 2: accessp.AccessService.ListRepos:output_type -> accessp.ListReposResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_access_proto_init() }
func file_access_proto_init() {
	if File_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_access_proto_rawDesc), len(file_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_access_proto_goTypes,
		DependencyIndexes: file_access_proto_depIdxs,
		MessageInfos:      file_access_proto_msgTypes,
	}.Build()
	File_access_proto = out.File
	file_access_proto_goTypes = nil
	file_access_proto_depIdxs = nil
}
